//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages: Pages;
  pagesConnection: PagesConnection;
  actualites: Actualites;
  actualitesConnection: ActualitesConnection;
  evenements: Evenements;
  evenementsConnection: EvenementsConnection;
  temoignages: Temoignages;
  temoignagesConnection: TemoignagesConnection;
  partenaires: Partenaires;
  partenairesConnection: PartenairesConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryActualitesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActualitesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActualitesFilter>;
};


export type QueryEvenementsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEvenementsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EvenementsFilter>;
};


export type QueryTemoignagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTemoignagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TemoignagesFilter>;
};


export type QueryPartenairesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartenairesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartenairesFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};

export type DocumentFilter = {
  pages?: InputMaybe<PagesFilter>;
  actualites?: InputMaybe<ActualitesFilter>;
  evenements?: InputMaybe<EvenementsFilter>;
  temoignages?: InputMaybe<TemoignagesFilter>;
  partenaires?: InputMaybe<PartenairesFilter>;
  settings?: InputMaybe<SettingsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Pages | Actualites | Evenements | Temoignages | Partenaires | Settings | Folder;

export type PagesSections = {
  __typename?: 'PagesSections';
  _template?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  linkUrl?: Maybe<Scalars['String']['output']>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  heroImageAlt?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaUrl?: Maybe<Scalars['String']['output']>;
  ctaSecondaryLabel?: Maybe<Scalars['String']['output']>;
  ctaSecondaryUrl?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<PagesSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesSectionsFilter = {
  _template?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  linkUrl?: InputMaybe<StringFilter>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaUrl?: InputMaybe<StringFilter>;
  ctaSecondaryLabel?: InputMaybe<StringFilter>;
  ctaSecondaryUrl?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PagesSectionsFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Actualites = Node & Document & {
  __typename?: 'Actualites';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  date: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  coverImageAlt?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ActualitesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  coverImageAlt?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ActualitesConnectionEdges = {
  __typename?: 'ActualitesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Actualites>;
};

export type ActualitesConnection = Connection & {
  __typename?: 'ActualitesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ActualitesConnectionEdges>>>;
};

export type Evenements = Node & Document & {
  __typename?: 'Evenements';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  startDate: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  location: Scalars['String']['output'];
  address?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  coverImageAlt?: Maybe<Scalars['String']['output']>;
  registrationUrl?: Maybe<Scalars['String']['output']>;
  isPastEvent?: Maybe<Scalars['Boolean']['output']>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EvenementsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  startDate?: InputMaybe<DatetimeFilter>;
  endDate?: InputMaybe<DatetimeFilter>;
  location?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  coverImageAlt?: InputMaybe<StringFilter>;
  registrationUrl?: InputMaybe<StringFilter>;
  isPastEvent?: InputMaybe<BooleanFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EvenementsConnectionEdges = {
  __typename?: 'EvenementsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Evenements>;
};

export type EvenementsConnection = Connection & {
  __typename?: 'EvenementsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EvenementsConnectionEdges>>>;
};

export type Temoignages = Node & Document & {
  __typename?: 'Temoignages';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  quote: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TemoignagesFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  published?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TemoignagesConnectionEdges = {
  __typename?: 'TemoignagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Temoignages>;
};

export type TemoignagesConnection = Connection & {
  __typename?: 'TemoignagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TemoignagesConnectionEdges>>>;
};

export type Partenaires = Node & Document & {
  __typename?: 'Partenaires';
  name: Scalars['String']['output'];
  logo?: Maybe<Scalars['String']['output']>;
  websiteUrl?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartenairesFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  websiteUrl?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type PartenairesConnectionEdges = {
  __typename?: 'PartenairesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partenaires>;
};

export type PartenairesConnection = Connection & {
  __typename?: 'PartenairesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartenairesConnectionEdges>>>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName: Scalars['String']['output'];
  siteDescription?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  facebookUrl?: Maybe<Scalars['String']['output']>;
  instagramUrl?: Maybe<Scalars['String']['output']>;
  youtubeUrl?: Maybe<Scalars['String']['output']>;
  linkedinUrl?: Maybe<Scalars['String']['output']>;
  helloAssoUrl: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteDescription?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  facebookUrl?: InputMaybe<StringFilter>;
  instagramUrl?: InputMaybe<StringFilter>;
  youtubeUrl?: InputMaybe<StringFilter>;
  linkedinUrl?: InputMaybe<StringFilter>;
  helloAssoUrl?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePages: Pages;
  createPages: Pages;
  updateActualites: Actualites;
  createActualites: Actualites;
  updateEvenements: Evenements;
  createEvenements: Evenements;
  updateTemoignages: Temoignages;
  createTemoignages: Temoignages;
  updatePartenaires: Partenaires;
  createPartenaires: Partenaires;
  updateSettings: Settings;
  createSettings: Settings;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateActualitesArgs = {
  relativePath: Scalars['String']['input'];
  params: ActualitesMutation;
};


export type MutationCreateActualitesArgs = {
  relativePath: Scalars['String']['input'];
  params: ActualitesMutation;
};


export type MutationUpdateEvenementsArgs = {
  relativePath: Scalars['String']['input'];
  params: EvenementsMutation;
};


export type MutationCreateEvenementsArgs = {
  relativePath: Scalars['String']['input'];
  params: EvenementsMutation;
};


export type MutationUpdateTemoignagesArgs = {
  relativePath: Scalars['String']['input'];
  params: TemoignagesMutation;
};


export type MutationCreateTemoignagesArgs = {
  relativePath: Scalars['String']['input'];
  params: TemoignagesMutation;
};


export type MutationUpdatePartenairesArgs = {
  relativePath: Scalars['String']['input'];
  params: PartenairesMutation;
};


export type MutationCreatePartenairesArgs = {
  relativePath: Scalars['String']['input'];
  params: PartenairesMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};

export type DocumentUpdateMutation = {
  pages?: InputMaybe<PagesMutation>;
  actualites?: InputMaybe<ActualitesMutation>;
  evenements?: InputMaybe<EvenementsMutation>;
  temoignages?: InputMaybe<TemoignagesMutation>;
  partenaires?: InputMaybe<PartenairesMutation>;
  settings?: InputMaybe<SettingsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  pages?: InputMaybe<PagesMutation>;
  actualites?: InputMaybe<ActualitesMutation>;
  evenements?: InputMaybe<EvenementsMutation>;
  temoignages?: InputMaybe<TemoignagesMutation>;
  partenaires?: InputMaybe<PartenairesMutation>;
  settings?: InputMaybe<SettingsMutation>;
};

export type PagesSectionsMutation = {
  _template?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  linkUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaUrl?: InputMaybe<Scalars['String']['input']>;
  ctaSecondaryLabel?: InputMaybe<Scalars['String']['input']>;
  ctaSecondaryUrl?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PagesSectionsMutation>>>;
};

export type ActualitesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  coverImageAlt?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type EvenementsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  startDate?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  coverImageAlt?: InputMaybe<Scalars['String']['input']>;
  registrationUrl?: InputMaybe<Scalars['String']['input']>;
  isPastEvent?: InputMaybe<Scalars['Boolean']['input']>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TemoignagesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type PartenairesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  websiteUrl?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteDescription?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  facebookUrl?: InputMaybe<Scalars['String']['input']>;
  instagramUrl?: InputMaybe<Scalars['String']['input']>;
  youtubeUrl?: InputMaybe<Scalars['String']['input']>;
  linkedinUrl?: InputMaybe<Scalars['String']['input']>;
  helloAssoUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PagesPartsFragment = { __typename: 'Pages', title: string, seoTitle?: string | null, seoDescription?: string | null, heroTitle?: string | null, heroSubtitle?: string | null, heroImage?: string | null, heroImageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, ctaSecondaryLabel?: string | null, ctaSecondaryUrl?: string | null, sections?: Array<{ __typename: 'PagesSections', _template?: string | null, heading?: string | null, body?: string | null, linkUrl?: string | null } | null> | null };

export type ActualitesPartsFragment = { __typename: 'Actualites', title: string, slug: string, date: string, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, category?: string | null, author?: string | null, featured?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null };

export type EvenementsPartsFragment = { __typename: 'Evenements', title: string, slug: string, startDate: string, endDate?: string | null, location: string, address?: string | null, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, registrationUrl?: string | null, isPastEvent?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null };

export type TemoignagesPartsFragment = { __typename: 'Temoignages', name: string, role?: string | null, quote: string, image?: string | null, published?: boolean | null, order?: number | null };

export type PartenairesPartsFragment = { __typename: 'Partenaires', name: string, logo?: string | null, websiteUrl?: string | null, order?: number | null, published?: boolean | null };

export type SettingsPartsFragment = { __typename: 'Settings', siteName: string, siteDescription?: string | null, logo?: string | null, email: string, phone?: string | null, address?: string | null, facebookUrl?: string | null, instagramUrl?: string | null, youtubeUrl?: string | null, linkedinUrl?: string | null, helloAssoUrl: string };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, seoTitle?: string | null, seoDescription?: string | null, heroTitle?: string | null, heroSubtitle?: string | null, heroImage?: string | null, heroImageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, ctaSecondaryLabel?: string | null, ctaSecondaryUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'PagesSections', _template?: string | null, heading?: string | null, body?: string | null, linkUrl?: string | null } | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, seoTitle?: string | null, seoDescription?: string | null, heroTitle?: string | null, heroSubtitle?: string | null, heroImage?: string | null, heroImageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, ctaSecondaryLabel?: string | null, ctaSecondaryUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'PagesSections', _template?: string | null, heading?: string | null, body?: string | null, linkUrl?: string | null } | null> | null } | null } | null> | null } };

export type ActualitesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ActualitesQuery = { __typename?: 'Query', actualites: { __typename: 'Actualites', id: string, title: string, slug: string, date: string, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, category?: string | null, author?: string | null, featured?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ActualitesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActualitesFilter>;
}>;


export type ActualitesConnectionQuery = { __typename?: 'Query', actualitesConnection: { __typename?: 'ActualitesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ActualitesConnectionEdges', cursor: string, node?: { __typename: 'Actualites', id: string, title: string, slug: string, date: string, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, category?: string | null, author?: string | null, featured?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EvenementsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EvenementsQuery = { __typename?: 'Query', evenements: { __typename: 'Evenements', id: string, title: string, slug: string, startDate: string, endDate?: string | null, location: string, address?: string | null, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, registrationUrl?: string | null, isPastEvent?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EvenementsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EvenementsFilter>;
}>;


export type EvenementsConnectionQuery = { __typename?: 'Query', evenementsConnection: { __typename?: 'EvenementsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EvenementsConnectionEdges', cursor: string, node?: { __typename: 'Evenements', id: string, title: string, slug: string, startDate: string, endDate?: string | null, location: string, address?: string | null, excerpt?: string | null, coverImage?: string | null, coverImageAlt?: string | null, registrationUrl?: string | null, isPastEvent?: boolean | null, seoTitle?: string | null, seoDescription?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TemoignagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TemoignagesQuery = { __typename?: 'Query', temoignages: { __typename: 'Temoignages', id: string, name: string, role?: string | null, quote: string, image?: string | null, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TemoignagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TemoignagesFilter>;
}>;


export type TemoignagesConnectionQuery = { __typename?: 'Query', temoignagesConnection: { __typename?: 'TemoignagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TemoignagesConnectionEdges', cursor: string, node?: { __typename: 'Temoignages', id: string, name: string, role?: string | null, quote: string, image?: string | null, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PartenairesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartenairesQuery = { __typename?: 'Query', partenaires: { __typename: 'Partenaires', id: string, name: string, logo?: string | null, websiteUrl?: string | null, order?: number | null, published?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PartenairesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartenairesFilter>;
}>;


export type PartenairesConnectionQuery = { __typename?: 'Query', partenairesConnection: { __typename?: 'PartenairesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartenairesConnectionEdges', cursor: string, node?: { __typename: 'Partenaires', id: string, name: string, logo?: string | null, websiteUrl?: string | null, order?: number | null, published?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, siteName: string, siteDescription?: string | null, logo?: string | null, email: string, phone?: string | null, address?: string | null, facebookUrl?: string | null, instagramUrl?: string | null, youtubeUrl?: string | null, linkedinUrl?: string | null, helloAssoUrl: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, siteName: string, siteDescription?: string | null, logo?: string | null, email: string, phone?: string | null, address?: string | null, facebookUrl?: string | null, instagramUrl?: string | null, youtubeUrl?: string | null, linkedinUrl?: string | null, helloAssoUrl: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  seoTitle
  seoDescription
  heroTitle
  heroSubtitle
  heroImage
  heroImageAlt
  ctaLabel
  ctaUrl
  ctaSecondaryLabel
  ctaSecondaryUrl
  sections {
    __typename
    _template
    heading
    body
    linkUrl
  }
}
    `;
export const ActualitesPartsFragmentDoc = gql`
    fragment ActualitesParts on Actualites {
  __typename
  title
  slug
  date
  excerpt
  coverImage
  coverImageAlt
  category
  author
  featured
  seoTitle
  seoDescription
  body
}
    `;
export const EvenementsPartsFragmentDoc = gql`
    fragment EvenementsParts on Evenements {
  __typename
  title
  slug
  startDate
  endDate
  location
  address
  excerpt
  coverImage
  coverImageAlt
  registrationUrl
  isPastEvent
  seoTitle
  seoDescription
  body
}
    `;
export const TemoignagesPartsFragmentDoc = gql`
    fragment TemoignagesParts on Temoignages {
  __typename
  name
  role
  quote
  image
  published
  order
}
    `;
export const PartenairesPartsFragmentDoc = gql`
    fragment PartenairesParts on Partenaires {
  __typename
  name
  logo
  websiteUrl
  order
  published
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  siteDescription
  logo
  email
  phone
  address
  facebookUrl
  instagramUrl
  youtubeUrl
  linkedinUrl
  helloAssoUrl
}
    `;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const ActualitesDocument = gql`
    query actualites($relativePath: String!) {
  actualites(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ActualitesParts
  }
}
    ${ActualitesPartsFragmentDoc}`;
export const ActualitesConnectionDocument = gql`
    query actualitesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ActualitesFilter) {
  actualitesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ActualitesParts
      }
    }
  }
}
    ${ActualitesPartsFragmentDoc}`;
export const EvenementsDocument = gql`
    query evenements($relativePath: String!) {
  evenements(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EvenementsParts
  }
}
    ${EvenementsPartsFragmentDoc}`;
export const EvenementsConnectionDocument = gql`
    query evenementsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EvenementsFilter) {
  evenementsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EvenementsParts
      }
    }
  }
}
    ${EvenementsPartsFragmentDoc}`;
export const TemoignagesDocument = gql`
    query temoignages($relativePath: String!) {
  temoignages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TemoignagesParts
  }
}
    ${TemoignagesPartsFragmentDoc}`;
export const TemoignagesConnectionDocument = gql`
    query temoignagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TemoignagesFilter) {
  temoignagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TemoignagesParts
      }
    }
  }
}
    ${TemoignagesPartsFragmentDoc}`;
export const PartenairesDocument = gql`
    query partenaires($relativePath: String!) {
  partenaires(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartenairesParts
  }
}
    ${PartenairesPartsFragmentDoc}`;
export const PartenairesConnectionDocument = gql`
    query partenairesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartenairesFilter) {
  partenairesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartenairesParts
      }
    }
  }
}
    ${PartenairesPartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    actualites(variables: ActualitesQueryVariables, options?: C): Promise<{data: ActualitesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActualitesQueryVariables, query: string}> {
        return requester<{data: ActualitesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActualitesQueryVariables, query: string}, ActualitesQueryVariables>(ActualitesDocument, variables, options);
      },
    actualitesConnection(variables?: ActualitesConnectionQueryVariables, options?: C): Promise<{data: ActualitesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActualitesConnectionQueryVariables, query: string}> {
        return requester<{data: ActualitesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActualitesConnectionQueryVariables, query: string}, ActualitesConnectionQueryVariables>(ActualitesConnectionDocument, variables, options);
      },
    evenements(variables: EvenementsQueryVariables, options?: C): Promise<{data: EvenementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EvenementsQueryVariables, query: string}> {
        return requester<{data: EvenementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EvenementsQueryVariables, query: string}, EvenementsQueryVariables>(EvenementsDocument, variables, options);
      },
    evenementsConnection(variables?: EvenementsConnectionQueryVariables, options?: C): Promise<{data: EvenementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EvenementsConnectionQueryVariables, query: string}> {
        return requester<{data: EvenementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EvenementsConnectionQueryVariables, query: string}, EvenementsConnectionQueryVariables>(EvenementsConnectionDocument, variables, options);
      },
    temoignages(variables: TemoignagesQueryVariables, options?: C): Promise<{data: TemoignagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemoignagesQueryVariables, query: string}> {
        return requester<{data: TemoignagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemoignagesQueryVariables, query: string}, TemoignagesQueryVariables>(TemoignagesDocument, variables, options);
      },
    temoignagesConnection(variables?: TemoignagesConnectionQueryVariables, options?: C): Promise<{data: TemoignagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemoignagesConnectionQueryVariables, query: string}> {
        return requester<{data: TemoignagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TemoignagesConnectionQueryVariables, query: string}, TemoignagesConnectionQueryVariables>(TemoignagesConnectionDocument, variables, options);
      },
    partenaires(variables: PartenairesQueryVariables, options?: C): Promise<{data: PartenairesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartenairesQueryVariables, query: string}> {
        return requester<{data: PartenairesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartenairesQueryVariables, query: string}, PartenairesQueryVariables>(PartenairesDocument, variables, options);
      },
    partenairesConnection(variables?: PartenairesConnectionQueryVariables, options?: C): Promise<{data: PartenairesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartenairesConnectionQueryVariables, query: string}> {
        return requester<{data: PartenairesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartenairesConnectionQueryVariables, query: string}, PartenairesConnectionQueryVariables>(PartenairesConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  